CUDA_VISIBLE_DEVICES=0 wandb agent zangzelin/SCLMAP/0ch40suk & 
CUDA_VISIBLE_DEVICES=1 wandb agent zangzelin/SCLMAP/0ch40suk & 
CUDA_VISIBLE_DEVICES=2 wandb agent zangzelin/SCLMAP/0ch40suk & 
CUDA_VISIBLE_DEVICES=0 wandb agent zangzelin/SCLMAP/0ch40suk & 
CUDA_VISIBLE_DEVICES=1 wandb agent zangzelin/SCLMAP/0ch40suk & 
CUDA_VISIBLE_DEVICES=2 wandb agent zangzelin/SCLMAP/0ch40suk & 
# CUDA_VISIBLE_DEVICES=3 wandb agent zangzelin/SCLMAP/0ch40suk & 
CUDA_VISIBLE_DEVICES=4 wandb agent zangzelin/SCLMAP/0ch40suk & 
CUDA_VISIBLE_DEVICES=5 wandb agent zangzelin/SCLMAP/0ch40suk & 
CUDA_VISIBLE_DEVICES=6 wandb agent zangzelin/SCLMAP/0ch40suk & 
CUDA_VISIBLE_DEVICES=4 wandb agent zangzelin/SCLMAP/0ch40suk & 
CUDA_VISIBLE_DEVICES=5 wandb agent zangzelin/SCLMAP/0ch40suk & 
CUDA_VISIBLE_DEVICES=6 wandb agent zangzelin/SCLMAP/0ch40suk & 
# CUDA_VISIBLE_DEVICES=7 wandb agent zangzelin/SCLMAP/0ch40suk & 